server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL='jdbc:mysql://lecture-archive-db.c1o480q8wvhq.ap-northeast-2.rds.amazonaws.com:3306/lecture_archive?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul'}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:TrailAdmin123!}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

cloud:
  aws:
    region: ap-northeast-2
    s3:
      bucket: snuti-exp-archive-images

app:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-this-to-a-long-secret}
    issuer: lecture-archive
    access-token-exp-minutes: 60
  cdn:
    base-url: https://snuti-exp-archive-images.s3.ap-northeast-2.amazonaws.com
